export const SET_ALL_BOOKS = "SET_ALL_BOOKS";
export const SET_FILTER_BOOKS = "SET_FILTER_BOOKS";
export const SET_SELECTED_BOOK = "SET_SELECTED_BOOK";
export const SET_LOADING = "SET_LOADING";
export const SET_PAGINATION = 'SET_PAGINATION';